file = open("timeone.txt", "r")
timeone=file.readline()
file.close()
print(timeone, end="")
file = open("timetwo.txt", "r")
timetwo=file.readline()
file.close()
print(timetwo, end="")
file = open("timethree.txt", "r")
timethree=file.readline()
file.close()
print(timethree, end="")
print("okay?")

